"""Regenerates TOKEN_USAGE_LOG.md from the raw JSONL usage log written by
backend/agents/llm_factory.py's per-call callback. Run after any smoke test
or work session to keep the human-readable log accurate.

Usage:
    uv run python -m backend.scripts.token_usage_report
"""

import json
from collections import defaultdict

from backend.agents.llm_factory import PRICING, estimate_cost
from backend.config import REPO_ROOT, get_settings


def main() -> None:
    settings = get_settings()
    log_path = settings.resolved_path(settings.token_usage_log_path)
    if not log_path.exists():
        print(f"No usage log found at {log_path} — no live calls recorded yet.")
        return

    totals: dict[tuple[str, str], dict[str, float]] = defaultdict(
        lambda: {
            "input": 0,
            "output": 0,
            "cache_creation": 0,
            "cache_read": 0,
            "calls": 0,
            "cost": 0.0,
            "latency_sum_ms": 0,
            "latency_count": 0,
        }
    )
    with log_path.open(encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line:
                continue
            row = json.loads(line)
            key = (row["agent"], row["model"])
            stats = totals[key]
            input_tokens = row.get("input_tokens") or 0
            output_tokens = row.get("output_tokens") or 0
            cache_creation = row.get("cache_creation_input_tokens") or 0
            cache_read = row.get("cache_read_input_tokens") or 0
            stats["input"] += input_tokens
            stats["output"] += output_tokens
            stats["cache_creation"] += cache_creation
            stats["cache_read"] += cache_read
            stats["calls"] += 1
            # Older log rows (pre cache-tracking) don't carry `estimated_cost`
            # — recompute from what they do have rather than skip them.
            stats["cost"] += (
                row["estimated_cost"]
                if row.get("estimated_cost") is not None
                else estimate_cost(row["model"], input_tokens, output_tokens, cache_creation, cache_read)
            )
            if row.get("latency_ms") is not None:
                stats["latency_sum_ms"] += row["latency_ms"]
                stats["latency_count"] += 1

    lines = [
        "# Token Usage Log",
        "",
        "Auto-generated by `backend/scripts/token_usage_report.py` from",
        "`storage/token_usage.jsonl` (per-call ground truth via LangChain's",
        "`usage_metadata`, including Anthropic prompt-cache read/write token",
        "counts once a call uses `AnthropicPromptCachingMiddleware`) — do not",
        "hand-edit this file.",
        "",
        "| Agent | Model | Calls | Input tokens | Cache write | Cache read | Output tokens | Avg latency | Est. cost |",
        "|---|---|---|---|---|---|---|---|---|",
    ]

    grand = {"input": 0, "output": 0, "cache_creation": 0, "cache_read": 0, "calls": 0, "cost": 0.0}
    for (agent, model), stats in sorted(totals.items()):
        avg_latency = (
            f"{round(stats['latency_sum_ms'] / stats['latency_count']):,} ms"
            if stats["latency_count"]
            else "n/a"
        )
        lines.append(
            f"| {agent} | {model} | {stats['calls']} | {stats['input']:,} | "
            f"{stats['cache_creation']:,} | {stats['cache_read']:,} | {stats['output']:,} | "
            f"{avg_latency} | ${stats['cost']:.4f} |"
        )
        for k in ("input", "output", "cache_creation", "cache_read", "calls"):
            grand[k] += stats[k]
        grand["cost"] += stats["cost"]

    lines.append(
        f"| **Total** | | **{grand['calls']}** | **{grand['input']:,}** | "
        f"**{grand['cache_creation']:,}** | **{grand['cache_read']:,}** | **{grand['output']:,}** | | "
        f"**${grand['cost']:.4f}** |"
    )
    lines.append("")
    pricing_note = ", ".join(f"{model}=${rates[0]}/${rates[1]}" for model, rates in PRICING.items())
    lines.append(f"Pricing used (per million tokens, input/output): {pricing_note}")
    lines.append("Models not in that list are priced at $0 — add them to `PRICING` in `backend/agents/llm_factory.py`.")
    lines.append(
        "Cache write is priced at 1.25x the input rate, cache read at 0.1x "
        "(Anthropic's 5-minute-TTL rates, matching `AnthropicPromptCachingMiddleware`'s default)."
    )

    report = "\n".join(lines) + "\n"
    output_path = REPO_ROOT / "TOKEN_USAGE_LOG.md"
    output_path.write_text(report, encoding="utf-8")
    print(report)
    print(f"Written to {output_path}")


if __name__ == "__main__":
    main()
